{
 "title": "Go Metrics",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(go_goroutines, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(go_goroutines{ namespace=\"$namespace\"},  service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{namespace=\"$namespace\", service=\"$service\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{pod}} ( {{instance}} )"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{ namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{pod}} ( {{instance}} )"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{ namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{pod}} ( {{instance}} )"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{ namespace=\"$namespace\", service=\"$service\"} - go_memstats_frees_total{ namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{pod}} ( {{instance}} )"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{ namespace=\"$namespace\", service=\"$service\"} ",
     "legendFormat": "{{pod}} ( {{instance}} )"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{ namespace=\"$namespace\", service=\"$service\"}[1m])",
     "legendFormat": "{{pod}} ( {{instance}} )"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{ namespace=\"$namespace\", service=\"$service\"}[1m])",
     "legendFormat": "{{pod}} ( {{instance}} )"
    }
   ]
  }
 ]
}