apiVersion: v1
kind: Service
metadata:
  name: svc-kubelilin-apiserver
  namespace: kube-lilin
  labels:
    app: kubelilin-apiserver
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: kubelilin-apiserver