yoyogo:
  application:
    name: kubelilin-apiserver
    metadata: "release"
    server:
      type: "fasthttp"
      address: ":8080"
      max_request_size: 2096157
      mvc:
        template: "v1/{controller}/{action}"
      cors:
        allow_origins: ["*"]
        allow_methods: ["*"]
        allow_credentials: false
      jwt:
        header: "Authorization"
        secret: "12391JdeOW^%$#@"
        prefix: "Bearer"
        expires: 360000
        enable: true
        skip_path: [
          "/v1/user/login",
          "/v1/pod/terminal",
          "/v1/deployment/executedeployment",
          "/v1/deployment/notify",
          "/actuator/health/liveness",
          "/actuator/health/readiness",
          "/actuator/health/detail",
          "/actuator/metrics",
        ]
  datasource:
    pool:
      init_cap: 2
      max_cap: 5
      idle_timeout: 5
    db:
      name: db1
      type: mysql
      url: ${PAAS_DB_CONN:tcp(127.0.0.1)/sgr_pass?charset=utf8mb4&loc=Local&parseTime=True}
      username: ${PAAS_DB_USER:root}
      password: ${PAAS_DB_PWD:root}
      debug: true


