yoyogo:
  application:
    name: sgr_platform_api
    metadata: "develop"
    server:
      type: "fasthttp"
      address: ":8080"
      max_request_size: 2096157
      mvc:
        template: "v1/{controller}/{action}"
      cors:
        allow_origins: ["*"]
        allow_methods: ["*"]
        allow_credentials: false
      jwt:
        header: "Authorization"
        secret: "12391JdeOW^%$#@"
        prefix: "Bearer"
        expires: 360000
        enable: true
        skip_path: [
          "/v1/user/login",
          "/v1/pod/terminal",
          "v1/deployment/executedeployment",
        ]
  datasource:
    pool:
      init_cap: 2
      max_cap: 5
      idle_timeout: 5
    db:
      name: db1
      type: mysql
      url: tcp(47.100.213.49:3306)/sgr_pass?charset=utf8&parseTime=True
      username: root
      password: P@ssW0rd
      debug: true
    redis:
      name: reids1
      url: 47.100.213.49:6379
      password: P@ssW0rd
      db: 0
vcs:
  git:
    url: https://gogs.xiaocui.site
    token: d2911632a4ac8db4ce13a3135700b58a5c8d7772
    username: sgr
    password: admin123
hub:
  harbor:
    url: https://harbor.xiaocui.site
    username: admin
    password: Harbor12345
    token: YWRtaW46SGFyYm9yMTIzNDU=
pipeline:
  jenkins:
    k8s-namespace: sgr-ci
    username: jenkins
    token: 11d32a54cd6150bd626d8ed73c3bfa02d6

