yoyogo:
  application:
    name: sgr_platform_api
    metadata: "develop"
    server:
      type: "fasthttp"
      address: ":8080"
      max_request_size: 2096157
      mvc:
        template: "v1/{controller}/{action}"
      cors:
        allow_origins: ["*"]
        allow_methods: ["*"]
        allow_credentials: true
      jwt:
        header: "Authorization"
        secret: "12391JdeOW^%$#@"
        prefix: "Bearer"
        expires: 360000
        enable: true
        skip_path: [
            "/v1/user/login",
            "/v1/pod/terminal",
        ]
  datasource:
    pool:
      init_cap: 2
      max_cap: 5
      idle_timeout: 5
    db:
      name: db1
      type: mysql
      url: tcp(mysql:3306)/sgr_pass?charset=utf8&parseTime=True
      username: root
      password: P@ssW0rd
      debug: true
