name: Compile&Publish

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.0"
        
      - name: Build kubelilin apiserver
        run: |
          go env -w GOPROXY=https://goproxy.cn,direct
          cd src
          go mod tidy 
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o app .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: github.event_name != 'pull_request'
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        if: github.event_name != 'pull_request'
      

      - name: Build And Push kubelilin apiserver
        uses: docker/build-push-action@v3
        with:
          context: src
          file: src/Dockerfile_Prod
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/kubelilin-apiserver:latest
        if: github.event_name != 'pull_request'
